💚 debugging typo with globals file

diff --git a/.github/workflows/CICD.yml b/.github/workflows/CICD.yml
--- a/.github/workflows/CICD.yml
+++ b/.github/workflows/CICD.yml
@@ -59,35 +59,16 @@ jobs:
           sshpass -p ${{ secrets.DEPLOY_PASSWORD }} scp -o StrictHostKeyChecking=no -r .next/* ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:${{ secrets.DEPLOY_PATH }}/.next
           sshpass -p ${{ secrets.DEPLOY_PASSWORD }} scp -o StrictHostKeyChecking=no -r public/* ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:${{ secrets.DEPLOY_PATH }}/public
           sshpass -p ${{ secrets.DEPLOY_PASSWORD }} scp -o StrictHostKeyChecking=no -r app/* ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:${{ secrets.DEPLOY_PATH }}/app
+
+          # Verify the CSS file is deployed
           sshpass -p ${{ secrets.DEPLOY_PASSWORD }} ssh -o StrictHostKeyChecking=no ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} << 'EOF'
-            # Install nvm
-            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
-            export NVM_DIR="$HOME/.nvm"
-            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
-
-            # Install and use Node.js 18
-            nvm install 18
-            nvm use 18
-            nvm alias default 18
-
-            # Configure npm to use user directory for global installs
-            mkdir -p ~/.npm-global
-            npm config set prefix '~/.npm-global'
-            export PATH=~/.npm-global/bin:$PATH
-            source ~/.profile
-
-            # Install PM2 globally
-            npm install -g pm2
-
-            # Navigate to the deployment path
-            cd ${{ secrets.DEPLOY_PATH }}
-
-            # Install project dependencies
-            rm -rf node_modules package-lock.json
-            npm install
-
-            # Restart or start the application using PM2
-            pm2 restart nextjs-app || pm2 start npm --name "nextjs-app" -- start
+            # Check the existence of the globals.css file
+            if [ -f "${{ secrets.DEPLOY_PATH }}/app/globals.css" ]; then
+              echo "globals.css file exists."
+            else
+              echo "globals.css file is missing!"
+              exit 1
+            fi
           EOF
       - name: Completed deployment message
         run: echo "Deployed app to server"
