💚 fixing ci/cd build

diff --git a/.github/workflows/CICD.yml b/.github/workflows/CICD.yml
--- a/.github/workflows/CICD.yml
+++ b/.github/workflows/CICD.yml
@@ -69,9 +69,18 @@ jobs:
           # Connect to the server to install dependencies and restart the application
           sshpass -p $SSH_PASS ssh -o StrictHostKeyChecking=no $REMOTE_USER@$REMOTE_HOST << 'EOF'
             cd $REMOTE_PROJECT_PATH
+
+            # Verify the CSS file is deployed
+            if [ -f "app/globals.css" ]; then
+              echo "globals.css file exists."
+            else
+              echo "globals.css file is missing!"
+              exit 1
+            fi
+
             npm install
             pm2 restart nextjs-app || pm2 start npm --name "nextjs-app" -- start
           EOF
-          
+
       - name: Completed deployment message
         run: echo "Deployed app to server"
